apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - alertmanager-config.yaml
  - alertmanager-deployment.yaml
  - alertmanager-service.yaml
  - grafana-dashboards.yaml
  - grafana-datasources.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - prometheus-rbac.yaml
  - prometheus-rules.yaml
  - prometheus-service.yaml
  - webhook-sink.yaml
