apiVersion: v1
kind: Service
metadata:
  name: model-server
  labels:
    app: model-server
spec:
  type: ClusterIP
  selector:
    app: model-server
    track: stable
  ports:
    - name: http
      port: 80
      targetPort: http
